### PR TITLE
Changes to implement OAuth2 based authentication

### PR DESCRIPTION
**Pull request by nitinjavakid**
Use OAuth2 based authentication

### CODE REVIEW

**Comment by rdohms** [comment]
@nitinjavakid seems like a good start, i'm going to push ahead with the guzzle 6 rewrite, but this could smooth it over while i get back into this.

Can you write some tests for these classes?
And go ahead and drop all the php 5.* from travis config.

**Comment by nitinjavakid** [comment]
Done.

**Comment by interludic** [comment]
Sorry to keep bugging...

How are you guys getting and setting the 'access_token' ?

Also whats the best way to bring this into the project? I couldn't find this through composer so, i am just updating the vendor directory manually from a zip downloaded from github. But obviously i will not be able to composer update from now on...

**Comment by pavlakis** [comment]
@interludic I've used https://gitlab.com/WitteStier/oauth2-meetup which supports the PHP League OAuth2 package.

You can take some ideas from my implementation here: https://github.com/pavlakis/notts-digital/tree/feature/create-oauth2-meetup-authorisation

**Review by rdohms — APPROVED** [review]

**Pull request merged**
