### PR TITLE
Renaming Guzzle to GuzzleHttp since it has changed

### PR DESCRIPTION
**Pull request by rscafi**
When running `composer install`/`update`:
>Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
**`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`**
Writing lock file
Generating autoload files

Reference:

https://packagist.org/packages/guzzle/guzzle
> This package is abandoned and no longer maintained. The author suggests using the guzzlehttp/guzzle package instead.

https://packagist.org/packages/guzzlehttp/guzzle

(also, `composer.lock` has been updated)

### CODE REVIEW

**Comment by azine** [comment]
+1

**Comment by rdohms** [comment]
@rscafi Thank you, but guzzlehttp is fo version 5. Unfortunately Guzzle decided to move forward with versions without bringing things like services and commands along, so we are waiting for those to be stable in v6 to make an upgrade.

For now we will remain on v3.

**Comment by rscafi** [comment]
Are you sure? If you check the lock file, it used `v3.8.1` of guzzlehttp.
Also, all tags are listed here:
https://packagist.org/packages/guzzlehttp/guzzle#v3.8.1

**Comment by rdohms** [comment]
@rscafi yes, it is possible to use that package, but the other one is not going away, and either way, v3 is deprecated, so there is not much gain either way.

Both packages point to the same repo as it is.

**Pull request closed without merging**
